### ISSUE TITLE
Hunger In Spleef

### ISSUE THREAD

**Issue by JettKuso** [Runsafe/SatingSpleefers#1]
While in the spleef area your hunger drains. Resulting in that you can not sprint anymore.

**Comment by mortenn** [comment]
You know.. in a way, I like that..
Makes long matches a bit more dynamic.
But everyone should start the match on the same fed and saturated levels.

**Comment by Kruithne** [comment]
We could hack in a quick fix: Put hunger/saturation level support in EventEngine and make the lobby auto-heal on enter/leave.

**Comment by Kruithne** [comment]
This has been fixed with WorldGuard.
